title: femgenerated
author: Vardhan Agrawal
email: vardhan@cs.stanford.edu
description: >-
  A unique digital exhibit where technology meets critical inquiry. Our platform offers an insightful journey into the world of generative AI, exploring the subtle yet profound ways in which the prompts we use shape the AI's understanding of race, religion, national origin, age, sex, disability, and veteran status.

social:
  twitter: vhanagwal
  facebook: vhanagwal
  instagram: vhanagwal
  github: vhanagwal
  linkedin: vhanagwal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
